[book]
title = "ChiFiAgent"
authors = ["Sha1rholder"]
language = "en"

[build]
build-dir = "book"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Sha1rholder/ChiFiAgent"
site-url = "/ChiFiAgent/"
